#!/usr/bin/perl
$classname = $ARGV[0];
$upcase = uc($classname);

open FILE, ">$classname.h";


print FILE <<EOF 
/************************************************
* $classname.h                                  *
*                                               *
* This file is part of dvisvgm                  *
* Copyright (c) 2005 by Martin Gieseking        *
************************************************/
// \$Id\$

EOF
;

print FILE "#ifndef $upcase" . "_H\n";
print FILE "#define $upcase" . "_H\n";

print FILE <<EOF

class $classname
{
   public:
      $classname ();
      ~$classname ();

   private:
};

#endif
EOF
;
close FILE;

open FILE, ">$classname.cpp";
print FILE <<EOF
/************************************************
* $classname.cpp                                *
*                                               *
* This file is part of dvisvgm                  *
* Copyright (c) 2005 by Martin Gieseking        *
************************************************/
// \$Id\$

#include "$classname.h"

using namespace std;


$classname\:\:$classname () {
}

EOF
;
close FILE;
