#!/bin/sh
# This file is part of the dvisvgm package and published under the
# terms of the GNU General Public License version 3 or later.
# See file COPYING for further details.
# (C) 2009-2015 Martin Gieseking <martin.gieseking@uos.de>

out=Makefile.am
cat >$out <<EOT
## This file is part of dvisvgm
## Copyright (C) 2005-2015 Martin Gieseking <martin.gieseking@uos.de>
##
## Process this file with automake.

AM_CXXFLAGS = -I\$(top_srcdir)/src -Wall -DSRCDIR='"\$(srcdir)"' \$(CODE_COVERAGE_CFLAGS)

TESTS =
check_PROGRAMS =

EOT

for f in *.cpp; do
	base=`basename $f .cpp`
	cat >>$out <<EOT
TESTS += $base
check_PROGRAMS += $base
${base}_SOURCES = $f
${base}_LDADD = ../src/libdvisvgm.a ../src/gzstream.o ../xxHash/libxxhash.a -L../potracelib -lpotrace -lfreetype -lgtest -lgtest_main -lpthread \$(CODE_COVERAGE_LDFLAGS)

EOT
done

echo "TESTDATA =" >>$out

for f in *.dvi; do
	base=`basename $f .dvi`
   echo  "TESTDATA += ${base}.dvi ${base}-wf-cmp.svg ${base}-nf-cmp.svg" >>$out
done

cat >>$out <<EOT
EXTRA_DIST = check-conv normalize.xsl cmr10.600gf sample.sfd \$(TESTDATA)
TESTS += check-conv

@CODE_COVERAGE_RULES@

CLEANFILES = *.gcda *.gcno
EOT

# vim: set syntax=sh:
