#!/bin/sh
# This file is part of the dvisvgm package and published under the 
# terms of the GNU General Public License version 3 or later.
# See file COPYING for further details.
# (C) 2009-2012 Martin Gieseking <martin.gieseking@uos.de>

out=Makefile.am
cat >$out <<EOT
## This file is part of dvisvgm
## Copyright (C) 2005-2012 Martin Gieseking <martin.gieseking@uos.de>
##
## Process this file with automake.

AM_CXXFLAGS = -I\$(srcdir)/../src -I\$(srcdir)/../../src -Wall -DSRCDIR='"\$(srcdir)"'

TESTS =
check_PROGRAMS =

EOT

for f in *.cpp; do
	base=`basename $f .cpp`
	cat >>$out <<EOT	
TESTS += $base
check_PROGRAMS += $base
${base}_SOURCES = $f
${base}_LDADD = ../src/libdvisvgm.a ../potracelib/libpotrace.a -lgtest -lgtest_main -lpthread

EOT
done

echo "TESTDATA =" >>$out

for f in *.dvi; do
	base=`basename $f .dvi`
   echo  "TESTDATA += ${base}.dvi ${base}-wf-cmp.svg ${base}-nf-cmp.svg" >>$out
done  

cat >>$out <<EOT
EXTRA_DIST = check-conv normalize.xsl cmr10.600gf \$(TESTDATA)
TESTS += check-conv
EOT

# vim: set syntax=sh: 
