/***********************************************************************
** cmdline.h                                                          **
**                                                                    **
** This file is part of dvisvgm -- the DVI to SVG converter           **
** Copyright (C) 2005-2006 Martin Gieseking <martin.gieseking@uos.de> **
**                                                                    **
** This program is free software; you can redistribute it and/or      **
** modify it under the terms of the GNU General Public License        **
** as published by the Free Software Foundation; either version 2     **
** of the License, or (at your option) any later version.             **
**                                                                    **
** This program is distributed in the hope that it will be useful,    **
** but WITHOUT ANY WARRANTY; without even the implied warranty of     **
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      **
** GNU General Public License for more details.                       **
**                                                                    **
** You should have received a copy of the GNU General Public License  **
** along with this program; if not, write to the Free Software        **
** Foundation, Inc., 51 Franklin Street, Fifth Floor,                 **
** Boston, MA 02110-1301, USA.                                        **
***********************************************************************/
// $Id$

/* File autogenerated by gengetopt version 2.14  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE PACKAGE
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  int page_arg;	/* choose page to convert (default='1').  */
  char * page_orig;	/* choose page to convert original value given at command line.  */
  char * bbox_format_arg;	/* set format of bounding box (default='min').  */
  char * bbox_format_orig;	/* set format of bounding box original value given at command line.  */
  char * output_arg;	/* set name of output file.  */
  char * output_orig;	/* set name of output file original value given at command line.  */
  int zip_arg;	/* create compressed .svgz file (default='3').  */
  char * zip_orig;	/* create compressed .svgz file original value given at command line.  */
  double rotate_arg;	/* rotate page content clockwise.  */
  char * rotate_orig;	/* rotate page content clockwise original value given at command line.  */
  char * scale_arg;	/* scale page content.  */
  char * scale_orig;	/* scale page content original value given at command line.  */
  char * translate_arg;	/* shift page content.  */
  char * translate_orig;	/* shift page content original value given at command line.  */
  char * transform_arg;	/* transform page content.  */
  char * transform_orig;	/* transform page content original value given at command line.  */
  double mag_arg;	/* magnification of Metafont output (default='4').  */
  char * mag_orig;	/* magnification of Metafont output original value given at command line.  */
  int specials_flag;	/* process \\specials (default=off).  */
  int verbosity_arg;	/* set verbosity level (0-7) (default='7').  */
  char * verbosity_orig;	/* set verbosity level (0-7) original value given at command line.  */
  
  int page_given ;	/* Whether page was given.  */
  int bbox_format_given ;	/* Whether bbox-format was given.  */
  int output_given ;	/* Whether output was given.  */
  int stdout_given ;	/* Whether stdout was given.  */
  int zip_given ;	/* Whether zip was given.  */
  int rotate_given ;	/* Whether rotate was given.  */
  int scale_given ;	/* Whether scale was given.  */
  int translate_given ;	/* Whether translate was given.  */
  int transform_given ;	/* Whether transform was given.  */
  int mag_given ;	/* Whether mag was given.  */
  int specials_given ;	/* Whether specials was given.  */
  int help_given ;	/* Whether help was given.  */
  int verbosity_given ;	/* Whether verbosity was given.  */
  int version_given ;	/* Whether version was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
